-- Baseline schema, matching the JPA entities in com.indusmind.domain exactly
-- (Spring's default camelCase -> snake_case column naming). Written to be
-- portable across PostgreSQL 12+ and H2 (MODE=PostgreSQL), since both are
-- used by this project (real deployments vs. the zero-config demo profile).

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    display_name VARCHAR(255) NOT NULL,
    role VARCHAR(255) NOT NULL,
    CONSTRAINT uk_users_username UNIQUE (username)
);

CREATE TABLE documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    original_name VARCHAR(255) NOT NULL,
    stored_name VARCHAR(255) NOT NULL,
    content_type VARCHAR(255),
    size_bytes BIGINT NOT NULL,
    status VARCHAR(255) NOT NULL,
    document_type VARCHAR(255),
    asset_tags VARCHAR(255),
    summary VARCHAR(1000),
    error_message VARCHAR(2000),
    uploaded_at TIMESTAMP
);

CREATE TABLE query_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question VARCHAR(1000) NOT NULL,
    answer VARCHAR(5000),
    mode VARCHAR(255),
    confidence DOUBLE PRECISION NOT NULL,
    created_at TIMESTAMP
);

CREATE INDEX idx_documents_status ON documents (status);
CREATE INDEX idx_query_logs_created_at ON query_logs (created_at);
