-- Adds support for: document ownership tracking, chat feedback, the audit
-- trail, and the structured asset registry. Written to be portable across
-- PostgreSQL 12+ and H2 (MODE=PostgreSQL), same as V1.

ALTER TABLE documents ADD COLUMN uploaded_by VARCHAR(255);

ALTER TABLE query_logs ADD COLUMN asset_tag VARCHAR(255);
ALTER TABLE query_logs ADD COLUMN feedback INTEGER;

CREATE TABLE audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor VARCHAR(255) NOT NULL,
    action VARCHAR(255) NOT NULL,
    target_type VARCHAR(255),
    target_id VARCHAR(255),
    detail VARCHAR(1000),
    created_at TIMESTAMP
);

CREATE TABLE assets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tag VARCHAR(255) NOT NULL,
    name VARCHAR(255),
    location VARCHAR(255),
    criticality VARCHAR(255),
    manufacturer VARCHAR(255),
    install_date DATE,
    notes VARCHAR(2000),
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT uk_assets_tag UNIQUE (tag)
);

CREATE INDEX idx_audit_logs_created_at ON audit_logs (created_at);
CREATE INDEX idx_audit_logs_actor ON audit_logs (actor);
